_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.9
        t:
            "3":
                - 16
                - 55
            "4": 3.12.9
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-arm64
epochs:
    value: 10
learning_rate:
    value: 0.01
