_wandb:
    value:
        cli_version: 0.20.1
        code_path: code/UAM-Toy-Env/train debug.py
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 22
                - 35
                - 55
            "4": 3.12.9
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-arm64
algo:
    value: PPO
total_timesteps:
    value: 500000
